### ISSUE TITLE
ts-node support/example?

### ISSUE THREAD

**Issue by kirillgroshkov** [wilk/microjob#54] opened 2019-12-09 23:59 UTC
Great library! Love the minimalistic API and 0 dependencies!

I just tried to use it for a little bit more complex example and it failed immediately with such code:

```typescript
await job(async accountId => {
  const account = await accountDao.getById(accountId)
  ...
}, {data: accountId})
```

What's happening here is that it's using some `accountDao` to fetch some thing from DB. This `accountDao` is imported above as:
```typescript
import {accountDao} from '@src/accountDao'
```

2 problems:
1. It can't find this module by such path (probably because `@src` is achieved using `tsconfig-paths`)
2. Even if I change it to some relative path like `./src/accountDao` or `../../src/accountDao` - no luck.

My next try to is to:
```typescript
require('ts-node/register')
const {accountDao} = require('./src/accountDao')
```

And then it's loaded! But then all its dependencies fail (cause they're still written in form of `@src/...`.

Any advice? Is it just me or someone else also having such issue?

I just cannot imaging the use of this module without using some dependent files, which doesn't work right now for a typescript project..

**Comment by jsalonen** [comment] 2019-12-10 12:38
I can confirm the same issue. Code loaded with `require` seems to work in ts-node, but `import` ... `from` doesn't.

**Comment by wilk** [comment] 2019-12-14 22:16
Mmm this is weird.
The scope of microjob's callback is not shared with its parent, meaning that you shouldn't be able to use `accountDao` in any form (both using `import` or `require`).
You're saying it is working with something like this?

```
require('ts-node/register')
const {accountDao} = require('./src/accountDao')

await job(async accountId => {
  const account = await accountDao.getById(accountId)
  ...
}, {data: accountId})
```

**Comment by kirillgroshkov** [comment] 2019-12-15 18:20
> Mmm this is weird.
> The scope of microjob's callback is not shared with its parent, meaning that you shouldn't be able to use `accountDao` in any form (both using `import` or `require`).
> You're saying it is working with something like this?

No, sorry, wasn't clear enough. It was working like this:

```typescript
await job(async accountId => {
  require('ts-node/register')
  const {accountDao} = require('./src/accountDao')
  const account = await accountDao.getById(accountId)
  ...
}, {data: accountId})
```

But such usage kills all the advantage of multithreading, since it takes significant time to transpile the code for each job invocation.

Probably I should just instantiate worker once and then stream input object there and receive a stream of outputs from it. But that's not the API that microjob offers, am I right?

**Comment by wilk** [comment] 2019-12-17 14:57
@kirillgroshkov 
Using `ts-node` in production is not recommended exactly for performance degradation.
Said that, you can do it both with `require` (and then compile) and by sending/receiving data to/from the worker.
`microjob` has a worker pool mechanism that preallocates a set of worker to increase run-time performance, so don't worry and go ahead with your project 😄

**Comment by wilk** [comment] 2020-01-21 14:23
I'm closing this.
If you think that the issue is still unsolved, please feel free to reopen it.

**Closed by wilk** 2020-01-21 14:23 UTC
Labels: question
